### ISSUE TITLE
Remove CUDA Sync Workaround in Evo2 Training Script

### ISSUE THREAD

**Issue by gagank1** [NVIDIA/bionemo-framework#1301]
There is a bug in TransformerEngine's LayerNormLinear where `self.layer_norm_weight` may not be fully initialized before the first forward pass due to asynchronous CUDA execution. It can contain garbage values instead of the expected initial values, causing NaNs and other potential issues. We have a workaround in place that sets `CUDA_LAUNCH_BLOCKING=1` before the first batch and removes it after to force synchronization on the first batch only. This needs to be removed once the bug is fixed upstream.

**Comment by jstjohn** [comment]
@gagank1 interestingly I'm having the same issue with a non-TE layer now: https://github.com/NVIDIA/bionemo-framework/blob/9dbcd2b559aa9a970fe6bcaf6e1602db2e1cde35/bionemo-recipes/recipes/evo2_megatron/src/bionemo/evo2/models/megatron/hyena/hyena_utils.py#L1247-L1253 Even though I reset the layer 4x during init currently, it only actually works if either:

1. I put pdb statements after each call to reset_parameters() which seems to block long enough
2. I run the job with `CUDA_LAUNCH_BLOCKING` like you mentioned.

So it's not just megatron/TE, wonder what's going on?

**Comment by jstjohn** [comment]
This is now fixed in megatron with https://github.com/NVIDIA/Megatron-LM/pull/2652

**Comment by jstjohn** [comment]
Addressed in megatron bridge here: https://github.com/NVIDIA-NeMo/Megatron-Bridge/pull/1706
